# Generated by Django 5.2.14 on 2026-06-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrador", "0013_historico_execucao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivosexecucao",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="execucao",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historico",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historico",
            name="situacao",
            field=models.CharField(
                choices=[("ANAPLAN", "ANAPLAN"), ("ERRO ANAPLAN", "ERRO ANAPLAN")],
                max_length=40,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="modelo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="parametrosexecucao",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="parametrosprocesslist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="processlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
